name: Aegis Guard CI + APIsec Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil playsound pillow pytest

      - name: Run Tests
        run: |
          pytest tests/ || true

  apisec-scan:
    name: APIsec Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger APIsec Scan
        env:
          APISEC_TOKEN: ${{ secrets.APISEC_TOKEN }}
        run: |
          echo "Starting APIsec scan..."
          curl -v -X POST "https://api.apisec.ai/scan" \
               -H "Authorization: Bearer $APISEC_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{"target":"https://example.com","scanType":"full"}'
