name: Aegis Guard CI + APIsec Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil playsound pillow pytest

      - name: Run Tests
        run: |
          pytest tests/ || true

  apisec-scan:
    name: APIsec Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger APIsec Scan Script
        env:
          APISEC_USERNAME: AegisGuardTeam
          APISEC_PASSWORD: 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
        run: |
          set -x
          ${GITHUB_ACTION_PATH}/apisec-run-scan.sh \
            --username AegisGuardTeam
            --password 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
            --project "VAmPI" \
            --profile "Master" \
            --scanner "" \
            --outputfile "apisec-results.sarif" \
            --refresh-playbooks "" \
            --host "https://example.com" \
            --emailReport "false" \
            --fail-on-vuln-severity "high" \
            --oas "false" \
            --openApiSpecUrl ""
